/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO_Driver.h"
#include "RCC_Driver.h"

GPIO_PINCONFIG_T RedLed =
{
		.pin = 14,
		.mode= GPIO_MODE_OUTPUT,
		.otype=GPIO_OTYPE_PP,
		.speed=GPIO_SPEED_LOW,
		.pupdr=GPIO_NO_PULL,
		.alternatefunc=0
};

void delay(void)
{
	for(uint32_t i=0; i< 1777777; i++);
}

int main(void)
{
	RCC_EnableGPIO(GPIOD);
	GPIO_Init(GPIOD, &RedLed);
	while(1)
	{
		GPIO_TogglePin(GPIOD, 14);
		delay();
	}
}
