/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO_Driver.h"
#include "RCC_Driver.h"
#include "SYSCONFIG_Driver.h"
#include "EXTI_Driver.h"
#include "NVIC_Driver.h"
#include "USART_Driver.h"

GPIO_PINCONFIG_T RedLed =
{
		.pin = 14,
		.mode= GPIO_MODE_OUTPUT,
		.otype=GPIO_OTYPE_PP,
		.speed=GPIO_SPEED_LOW,
		.pupdr=GPIO_NO_PULL,
		.alternatefunc=0
};

GPIO_PINCONFIG_T PushButton =
{
		.pin = 0,
		.mode= GPIO_MODE_INPUT,
		.otype=GPIO_OTYPE_OD,
		.speed=GPIO_SPEED_LOW,
		.pupdr=GPIO_NO_PULL,
		.alternatefunc=0
};

USART_Struct_T Usart2Struct =
{
		.baudrate = 9600,
		.oversampling = 8,
		.parity = USART_PARITY_NONE,
		.stopBits = USART_STOPBITS_1,
		.usartID = USART2_ID,
		.wordLength = USART_WORDLENGTH_8B
};

void delay(void)
{
	for(uint32_t i=0; i< 1777777; i++);
}

void Part15_InterruptDemo()
{
	/*Enable Push Button Port Clock - Port A*/
	RCC_EnableGPIO(GPIOA);

	/*Enable LED Port Clock - Port D*/
	RCC_EnableGPIO(GPIOD);

	/*Initialize LED Pin*/
	GPIO_Init(GPIOD, &RedLed);

	/*Initialize PushButton Pin*/
	GPIO_Init(GPIOA, &PushButton);

	/*Set the EXTI0 to PA0 through SYSCFG*/
	SYSCFG_SetEXTISource(0,0);

	/*Enable EXTI Line Interrupt*/
	EXTI_EnableInterrupt(0, EXTI_TRIGGER_RISING);

	/*Enable NVIC Interrupt for EXTI0*/
	NVIC_EnableIRQ(EXTI0_IRQn);
}

uint8_t RxBuff[10];
int main(void)
{
	/*Uncomment to execute Interrupt Demo*/
	//Part15_InterruptDemo();

	const char *message = "Hello from USART2!\n";
	//Enable FPU
	SCB_CPACR_ADDR |= (0xF << 20);

	//Enable the HSE Clock (8MHz) and configure the USART Peripheral Clock (APB Clock) also to 8MHz
	RCC_Config_HSE_SystemClock();

	USART_Init(&Usart2Struct);
	USART_Transmit(USART2_ID, (uint8_t*)message, 19);
	while(1)
	{
		USART_Receive(USART2_ID, (uint8_t*)RxBuff, 1);
		USART_Transmit(USART2_ID, (uint8_t*)RxBuff, 1);
	}
}



void EXTI0_IRQHandler()
{
	if(EXTI_IsPending(0) == 1)
	{
		GPIO_TogglePin(GPIOD, 14);
		EXTI_ClearPending(0);
	}
}
