/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define GPIOA_BASE_ADDR 	0x40020000U
#define GPIOB_BASE_ADDR		0x40020400U
#define GPIOC_BASE_ADDR		0x40020800U
#define GPIOD_BASE_ADDR		0x40020C00U
#define GPIOE_BASE_ADDR		0x40021000U
#define GPIOH_BASE_ADDR		0x40021C00U

/*Define the macros for GPIOx Registers offset*/

#define GPIOx_MODER_OFFSET 		0x00U
#define GPIOx_OTYPER_OFFSET 	0x04U
#define GPIOx_SPEEDR_OFFSET 	0x08U
#define GPIOx_PUPDR_OFFSET		0x0CU
#define GPIOx_IDR_OFFSET		0x10U
#define GPIOx_ODR_OFFSET		0x14U
#define GPIOx_BSRR_OFFSET		0x18U
#define GPIOx_LCKR_OFFSET		0x1CU
#define GPIOx_AFLR_OFFSET	  	0x20U
#define GPIOx_AFHR_OFFSET		0x24U

/*Actual GPIOD Register Address*/
#define GPIOD_MODER_ADDR 		(GPIOD_BASE_ADDR + GPIOx_MODER_OFFSET)
#define GPIOD_OTYPER_ADDR		(GPIOD_BASE_ADDR + GPIOx_OTYPER_OFFSET)
#define GPIOD_SPEEDR_ADDR		(GPIOD_BASE_ADDR + GPIOx_SPEEDR_OFFSET)
#define GPIOD_PUPDR_ADDR		(GPIOD_BASE_ADDR + GPIOx_PUPDR_OFFSET)
#define GPIOD_IDR_ADDR			(GPIOD_BASE_ADDR + GPIOx_IDR_OFFSET)
#define GPIOD_ODR_ADDR			(GPIOD_BASE_ADDR + GPIOx_ODR_OFFSET)
#define GPIOD_BSRR_ADDR			(GPIOD_BASE_ADDR + GPIOx_BSRR_OFFSET)
#define GPIOD_LCKR_ADDR			(GPIOD_BASE_ADDR + GPIOx_LCKR_OFFSET)
#define GPIOD_AFLR_ADDR			(GPIOD_BASE_ADDR + GPIOx_AFLR_OFFSET)
#define GPIOD_AFHR_ADDR			(GPIOD_BASE_ADDR + GPIOx_AFHR_OFFSET)

/*Actual GPIOA Register Addresses*/
#define GPIOA_MODER_ADDR 		(GPIOA_BASE_ADDR + GPIOx_MODER_OFFSET)
#define GPIOA_OTYPER_ADDR		(GPIOA_BASE_ADDR + GPIOx_OTYPER_OFFSET)
#define GPIOA_SPEEDR_ADDR		(GPIOA_BASE_ADDR + GPIOx_SPEEDR_OFFSET)
#define GPIOA_PUPDR_ADDR		(GPIOA_BASE_ADDR + GPIOx_PUPDR_OFFSET)
#define GPIOA_IDR_ADDR			(GPIOA_BASE_ADDR + GPIOx_IDR_OFFSET)
#define GPIOA_ODR_ADDR			(GPIOA_BASE_ADDR + GPIOx_ODR_OFFSET)
#define GPIOA_BSRR_ADDR			(GPIOA_BASE_ADDR + GPIOx_BSRR_OFFSET)
#define GPIOA_LCKR_ADDR			(GPIOA_BASE_ADDR + GPIOx_LCKR_OFFSET)
#define GPIOA_AFLR_ADDR			(GPIOA_BASE_ADDR + GPIOx_AFLR_OFFSET)
#define GPIOA_AFHR_ADDR			(GPIOA_BASE_ADDR + GPIOx_AFHR_OFFSET)

/*Macros related to RCC */
#define RCC_BASE_ADDR 				0x40023800UL
#define RCC_APB1ENR_OFFSET			0x40
#define RCC_APB1ENR_ADDR			(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)

#define RCC_CFGR_OFFSET				0x08
#define RCC_CFGR_ADDR				(RCC_BASE_ADDR + RCC_CFGR_OFFSET)

#define RCC_CR_ADDR					RCC_BASE_ADDR

#define RCC_AHB1ENR_OFFSET			0x30
#define RCC_AHB1ENR_ADDR			(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(void)
{
	for(uint32_t i=0; i< 1777777; i++);
}

int main(void)
{
	uint32_t *pGpiodModerAddr = (uint32_t*) GPIOD_MODER_ADDR;
	uint32_t *pGpiodPupdrAddr = (uint32_t*) GPIOD_PUPDR_ADDR;
	uint32_t *pGpiodOdrAddr   = (uint32_t*) GPIOD_ODR_ADDR;
	uint32_t *pRccAhb1EnrAddr = (uint32_t*) RCC_AHB1ENR_ADDR;
	uint32_t *pGpioaIdrAddr   = (uint32_t*) GPIOA_IDR_ADDR;

	//Enable Port A & D  Clock
	*pRccAhb1EnrAddr  |= ((1 << 3) | (1 <<0));

	// Configure PD12, PD13, PD14, PD15 as Output
	*pGpiodModerAddr  |= (0x55 << 24);

	//Activate Pull Down Resistors by default
	*pGpiodPupdrAddr  |= (0xAA << 24);


    /* Loop forever */
	for(;;)
	{
		if( *pGpioaIdrAddr & 1)
		{
			//Enable all LEDs
			*pGpiodOdrAddr    |= (0xF << 12);

		}
		else
		{
			//Turn off all LEDs
			*pGpiodOdrAddr    &= ~(0xF << 12);
		}
	}
}
