/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDR 				0x40023800UL
#define RCC_APB1ENR_OFFSET			0x40
#define RCC_APB1ENR_ADDR			(RCC_BASE_ADDR + RCC_APB1ENR_OFFSET)

#define RCC_CFGR_OFFSET				0x08
#define RCC_CFGR_ADDR				(RCC_BASE_ADDR + RCC_CFGR_OFFSET)

#define RCC_CR_ADDR					RCC_BASE_ADDR

#define RCC_AHB1ENR_OFFSET			0x30
#define RCC_AHB1ENR_ADDR			(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)

#define I2C1_BASE_ADDR				0x40005400UL
#define I2C1_CR2_OFFSET 			0x04
#define I2C1_CR2_ADDR				(I2C1_BASE_ADDR + I2C1_CR2_OFFSET)

#define GPIOA_BASE_ADDR				0x40020000UL
#define GPIOA_MODER_ADDR			GPIOA_BASE_ADDR


int main(void)
{
	uint32_t *pRccApb1EnrAddr  = (uint32_t*)RCC_APB1ENR_ADDR;
	uint32_t *pI2C1Cr2Addr 	   = (uint32_t*)I2C1_CR2_ADDR;
	uint32_t *pRccCrAddr	   = (uint32_t*)RCC_CR_ADDR;
	uint32_t *pGpioAModerAddr  = (uint32_t*)GPIOA_MODER_ADDR;
	uint32_t *pRccCfgrAddr	   = (uint32_t*)RCC_CFGR_ADDR;
	uint32_t *pRccAhb1EnrAddr  = (uint32_t*)RCC_AHB1ENR_ADDR;

	//Enabled APB1 Peripheral Clock for I2C1
	*pRccApb1EnrAddr |= (1 << 21);

	//Enabled 2MHz Freq for I2C1
    *pI2C1Cr2Addr  |= (0b000010 <<0);

    //Enable GPIOA Clock
    *pRccAhb1EnrAddr |= 1;

    //Enable HSE ON
    *pRccCrAddr |= (1 << 16);

    //Set Alternate Function in GPIOA - Pin8 (PA8 - MCO1)
    *pGpioAModerAddr |= (0b10 << 16);

    // By default the alternate function is MCO1

    // route HSE Osc to MCO1
    *pRccCfgrAddr |= (0b10 << 21);

    /* Loop forever */
	for(;;);
}
